##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Wed Sep 07 09:35:35 CEST 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = BionX32


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O3


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/display_s866.c \
Src/motorcontrol.c \
Src/mc_api.c \
Src/mc_config.c \
Src/mc_tasks.c \
Src/regular_conversion_manager.c \
Src/mc_math.c \
Src/mc_interface.c \
Src/stm32f10x_mc_it.c \
Src/mc_parameters.c \
Src/ui_task.c \
Src/user_interface.c \
Src/dac_rctimer_ui.c \
Src/stm32f1xx_it.c \
Src/stm32f1xx_hal_msp.c \
Src/putchars.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_exti.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c \
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c \
Src/system_stm32f1xx.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/hall_speed_pos_fdbk.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/motor_power_measurement.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pwm_curr_fdbk.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/pwm_common.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/state_machine.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c \
MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F1xx/Src/r1_vl1_pwm_curr_fdbk.c \
MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/dac_common_ui.c \
MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/frame_communication_protocol.c \
MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/ui_irq_handler.c \
MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Src/usart_frame_communication_protocol.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f103xe.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS =

# C defines
C_DEFS =  \
-DARM_MATH_CM3 \
-DUSE_HAL_DRIVER \
-DSTM32F103xE


# AS includes
AS_INCLUDES =

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/STM32F1xx_HAL_Driver/Inc \
-IDrivers/STM32F1xx_HAL_Driver/Inc/Legacy \
-I./MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/Any/Inc \
-I./MCSDK_v5.4.8/MotorControl/MCSDK/MCLib/F1xx/Inc \
-I./MCSDK_v5.4.8/MotorControl/MCSDK/UILibrary/Inc \
-I./MCSDK_v5.4.8/MotorControl/MCSDK/SystemDriveParams \
-IDrivers/CMSIS/Device/ST/STM32F1xx/Include \
-IDrivers/CMSIS/Include

#-I./Drivers/CMSIS/DSP/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
#LDSCRIPT = STM32F103RCTx_FLASH.ld
LDSCRIPT = STM32F103C8Tx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys  \
-l:libmc-gcc_M3.lib
LIBDIR =  \
-LMCSDK_v5.4.8/MotorControl/lib
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#
#  STLINK:           Controller
#
#     2      SWDIO
#     4      GND
#     6      SWCLK
#     8      VCC-3.3
#
flash:
	st-flash write $(BUILD_DIR)/$(TARGET).bin 0x08000000

info:
	st-flash --area=optcr read
	st-flash --area=option_boot_add read


#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
